# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steven Lee-Kramer
position: Fullstack Developer
email: sleekramer@gmail.com
description: "Steven Lee-Kramer -- Fullstack Developer Portfolio Site.  Developer specializing in Javascript, AngularJS, Node.js, JQuery, HTML5, CSS3, Ruby, and Rails. Has working knowledge of PHP, Python, Flask, Bash, Git."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username: sleekramer
linkedin_username: stevenleekramer
# Build settings
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: _sass
    style: :compressed


collections:
  portfolio:
    output: true
    permalink: /portfolio/:title
